# Generated by Django 2.0.3 on 2018-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='用户名称')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('sex', models.SmallIntegerField(choices=[(1, '男士'), (2, '女士')], default=1, verbose_name='性别')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(max_length=128, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Image/', verbose_name='头像')),
                ('openid', models.CharField(blank=True, max_length=128, null=True, verbose_name='openID')),
                ('personalized_signature', models.CharField(blank=True, max_length=128, null=True, verbose_name='个性签名')),
                ('data_joined', models.DateField(auto_now_add=True, verbose_name='加入日期')),
                ('last_login', models.DateField(auto_now=True, null=True, verbose_name='最近登录日期')),
                ('is_active', models.SmallIntegerField(choices=[(1, '男士'), (2, '女士')], default=1, verbose_name='账号状态')),
            ],
        ),
    ]
