# Generated by Django 2.0.3 on 2018-03-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180326_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='username',
            new_name='accountname',
        ),
    ]
