# Generated by Django 2.0.3 on 2018-03-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_auto_20180326_1556'),
        ('account', '0004_auto_20180326_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(blank=True, default=1)),
                ('bookname', models.CharField(blank=True, max_length=128, null=True, verbose_name='书名')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名')),
                ('chaptername', models.CharField(blank=True, max_length=128, null=True, verbose_name='章节名')),
                ('time', models.DateTimeField(auto_now=True, null=True, verbose_name='记录时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='accountname',
            new_name='username',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='记录时间'),
        ),
    ]
