# Generated by Django 2.0.3 on 2018-03-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180327_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, null=True, verbose_name='记录时间')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='prtid',
            field=models.IntegerField(default=0, verbose_name='回复ID'),
        ),
        migrations.AddField(
            model_name='comment',
            name='starnum',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='chapter',
            field=models.IntegerField(blank=True, default=1, verbose_name='章节编号'),
        ),
        migrations.AddField(
            model_name='star',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Comment'),
        ),
        migrations.AddField(
            model_name='star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
