# Generated by Django 2.0.3 on 2018-04-20 02:35

from django.db import migrations, models
import django.db.models.deletion
import novel.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'verbose_name': '书架', 'verbose_name_plural': '书架'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.SmallIntegerField(choices=[(0, '注销'), (1, '正常')], default=1, verbose_name='账号状态'),
        ),
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='Imag/default_img.jpg', null=True, storage=novel.utils.storage.ImageStorage(), upload_to='Imag/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Name', verbose_name='书编号'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='chapter',
            field=models.IntegerField(blank=True, default=1, verbose_name='章节编号'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='用户编号'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Name', verbose_name='书编号'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='用户编号'),
        ),
        migrations.AlterField(
            model_name='star',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Comment', verbose_name='评论编号'),
        ),
        migrations.AlterField(
            model_name='star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='用户编号'),
        ),
    ]
