# Generated by Django 2.0.3 on 2018-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaptername',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('xs_chaptername', models.CharField(max_length=255)),
                ('xs_content', models.TextField()),
                ('id_name', models.CharField(max_length=15)),
                ('num_id', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('xs_name', models.CharField(max_length=255)),
                ('xs_author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('name_id', models.CharField(max_length=255)),
            ],
        ),
    ]
