# Generated by Django 2.0.3 on 2018-03-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptername',
            options={'ordering': ['num_id']},
        ),
    ]
