# Generated by Django 2.0.3 on 2018-04-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_auto_20180326_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='allrank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='总榜'),
        ),
        migrations.AddField(
            model_name='name',
            name='monthrank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='周榜'),
        ),
        migrations.AddField(
            model_name='name',
            name='yearrank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='月榜'),
        ),
    ]
