# Generated by Django 2.0.3 on 2018-04-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_auto_20180420_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='url',
            field=models.CharField(default="{% url 'novel:index' %}", max_length=255, verbose_name='跳转URL'),
        ),
    ]
