# Generated by Django 2.0.3 on 2018-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_websetting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptername',
            name='num_id',
            field=models.IntegerField(verbose_name='章节号'),
        ),
    ]
