# Generated by Django 2.0.3 on 2018-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_auto_20180421_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptername',
            name='num_id',
            field=models.CharField(max_length=15, verbose_name='章节号'),
        ),
    ]
