# Generated by Django 2.0.3 on 2018-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_auto_20180423_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptername',
            name='num_id',
            field=models.IntegerField(verbose_name='章节号'),
        ),
    ]
