# Generated by Django 2.0.3 on 2018-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0011_auto_20180423_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptername',
            name='next',
            field=models.IntegerField(default=0, verbose_name='下一章'),
        ),
        migrations.AddField(
            model_name='chaptername',
            name='prev',
            field=models.IntegerField(default=0, verbose_name='上一章'),
        ),
    ]
