# Generated by Django 2.0.3 on 2018-05-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0012_auto_20180423_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptername',
            name='next',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='下一章'),
        ),
        migrations.AlterField(
            model_name='chaptername',
            name='prev',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='上一章'),
        ),
    ]
