# Generated by Django 2.0.3 on 2018-05-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0013_auto_20180515_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='pic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='name',
            name='summery',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='简介'),
        ),
    ]
